import { 
  EventItem, 
  Venue, 
  ScheduleItem, 
  Announcement, 
  ResultItem, 
  LeaderboardEntry, 
  Sponsor, 
  GalleryItem, 
  Registration, 
  Participant,
  NotificationItem,
  UserProfile,
  CertificateItem
} from '../types/database';

export const INITIAL_VENUES: Venue[] = [
  {
    id: 'v_auditorium',
    name: 'Dr. APJ Abdul Kalam Grand Auditorium',
    short_code: 'AUD-01',
    location: 'Central Campus, Block A',
    capacity: 1500,
    facilities: ['Central Air Conditioning', 'State-of-the-Art JBL Sound Rig', 'Stage Lighting Truss', '4 Green Rooms', 'Green Screen Backdrop'],
    latitude: 13.0827,
    longitude: 80.2707,
    image_url: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 'v_amphitheatre',
    name: 'Open Air Amphitheatre',
    short_code: 'OAT-02',
    location: 'North Quadrangle, Near Lake',
    capacity: 3000,
    facilities: ['Acoustic Shell', 'Stepped Stone Seating', 'Dual LED Video Walls', 'Open Sky Canopy', 'Broadcast Booth'],
    latitude: 13.0835,
    longitude: 80.2715,
    image_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 'v_sports_complex',
    name: 'Major Dhyan Chand Indoor Sports Arena',
    short_code: 'INDOOR-03',
    location: 'South Campus Sports Enclave',
    capacity: 800,
    facilities: ['Wooden Flooring', 'Stiga Competition Tables', 'Digital Scoreboards', 'Locker Rooms', 'Medical First Aid Bay'],
    latitude: 13.0815,
    longitude: 80.2690,
    image_url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 'v_stadium',
    name: 'University Main Stadium & Athletic Track',
    short_code: 'STAD-04',
    location: 'West Enclave Sports Complex',
    capacity: 2500,
    facilities: ['Floodlit Courts', 'Acrylic Synthetic Court', 'Pavilion Seating', 'Warm-up Enclosure', 'Commentary Box'],
    latitude: 13.0840,
    longitude: 80.2680,
    image_url: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 'v_seminar_complex',
    name: 'Vikram Sarabhai Seminar Complex',
    short_code: 'SEM-05',
    location: 'East Academic Wing, 2nd Floor',
    capacity: 350,
    facilities: ['Dual Laser Projectors', 'Dolby Surround Audio', 'Podium Mics', 'Tiered Executive Chairs', 'High Speed Wi-Fi'],
    latitude: 13.0820,
    longitude: 80.2725,
    image_url: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 'v_arts_studio',
    name: 'Raja Ravi Varma Fine Arts Pavilion',
    short_code: 'ART-06',
    location: 'Design Wing, Ground Floor',
    capacity: 250,
    facilities: ['Natural Skylight', 'Display Easels', 'Ceramic Wet Stations', 'Exhibition Hanging Rails', 'Wash Basins'],
    latitude: 13.0810,
    longitude: 80.2730,
    image_url: 'https://images.unsplash.com/photo-1460661419200-fd4ecdccc14d?auto=format&fit=crop&w=1200&q=80'
  }
];

export const INITIAL_EVENTS: EventItem[] = [
  // 1. Fine Arts
  {
    event_id: 'evt_cul_01',
    event_name: 'Fine Arts Exhibition & Live Canvas',
    category: 'cultural',
    sub_category: 'fine_arts',
    description: 'Unleash your visual imagination across watercolor, acrylics, sketching, and charcoal. Participants will be provided a central theme on the spot and 3 hours of uninterrupted creation.',
    rules: [
      'Medium: Acrylic, Watercolor, Charcoal or Mixed Media',
      'Standard A2 canvas/sheets provided by festival host',
      'Time limit: Exactly 3 hours',
      'Theme announced 15 minutes before commencement',
      'No digital aids or reference photos permitted during event'
    ],
    eligibility: 'Open to all bonafide college students with valid student ID card',
    participation_type: 'individual',
    team_size_min: 1,
    team_size_max: 1,
    registration_fee: 150,
    venue_id: 'v_arts_studio',
    venue: 'Raja Ravi Varma Fine Arts Pavilion',
    event_date: '2026-10-15',
    start_time: '10:00',
    end_time: '13:00',
    registration_deadline: '2026-10-13T23:59:59Z',
    maximum_participants: 40,
    current_participants: 24,
    status: 'open',
    event_image: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=1000&q=80',
    coordinator_name: 'Ananya Deshmukh',
    coordinator_contact: '+91 98451 22341',
    coordinator_email: 'finearts.colorido@university.edu'
  },
  // 2. Music & Band - Solo
  {
    event_id: 'evt_cul_02',
    event_name: 'Music & Band — Solo (Vocal / Instrumental)',
    category: 'cultural',
    sub_category: 'solo',
    description: 'A high-octane showcase of vocal prowess and solo acoustic dexterity. Bring your classical, contemporary, jazz, or rock acoustic pieces to mesmerize our jury.',
    rules: [
      'Time limit: 4 minutes performance + 2 minutes sound check',
      'Only one backing track or one accompanist allowed',
      'Profanity or vulgar lyrics leads to instant disqualification',
      'Original compositions receive bonus weighting'
    ],
    eligibility: 'College undergraduate & postgraduate students',
    participation_type: 'individual',
    team_size_min: 1,
    team_size_max: 1,
    registration_fee: 200,
    venue_id: 'v_auditorium',
    venue: 'Dr. APJ Abdul Kalam Grand Auditorium',
    event_date: '2026-10-15',
    start_time: '14:00',
    end_time: '17:30',
    registration_deadline: '2026-10-13T23:59:59Z',
    maximum_participants: 30,
    current_participants: 28,
    status: 'open',
    event_image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&q=80',
    coordinator_name: 'Rohan Kulkarni',
    coordinator_contact: '+91 98203 44129',
    coordinator_email: 'music.colorido@university.edu'
  },
  // 3. Music & Band - Group
  {
    event_id: 'evt_cul_03',
    event_name: 'Music & Band — Battle of the Bands (Group)',
    category: 'cultural',
    sub_category: 'group',
    description: 'The premier university rock and fusion battle. Full live setups featuring blistering guitar solos, thunderous bass lines, and electrifying percussion.',
    rules: [
      'Team size: 3 to 8 members',
      'Time limit: 12 minutes on stage including setup and teardown',
      'Standard 5-piece drum kit and guitar amps provided',
      'At least one original composition mandatory'
    ],
    eligibility: 'Inter-college music society teams',
    participation_type: 'team',
    team_size_min: 3,
    team_size_max: 8,
    registration_fee: 800,
    venue_id: 'v_amphitheatre',
    venue: 'Open Air Amphitheatre',
    event_date: '2026-10-16',
    start_time: '18:00',
    end_time: '22:00',
    registration_deadline: '2026-10-14T18:00:00Z',
    maximum_participants: 16,
    current_participants: 14,
    status: 'open',
    event_image: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=1000&q=80',
    coordinator_name: 'Vikramaditya Sen',
    coordinator_contact: '+91 97412 88902',
    coordinator_email: 'bands.colorido@university.edu'
  },
  // 4. Dance - Solo
  {
    event_id: 'evt_cul_04',
    event_name: 'Dance — Solo (Classical / Freestyle)',
    category: 'cultural',
    sub_category: 'solo',
    description: 'Command the center stage with breathtaking choreography, storytelling, and rhythm across Indian Classical, Hip-Hop, Contemporary, or Freestyle genres.',
    rules: [
      'Time limit: 3 to 4 minutes',
      'Track must be submitted in MP3 format 1 hour before round',
      'Props permitted with prior coordinator approval',
      'Costumes must strictly adhere to festival decency standards'
    ],
    eligibility: 'Open to individual student dancers',
    participation_type: 'individual',
    team_size_min: 1,
    team_size_max: 1,
    registration_fee: 200,
    venue_id: 'v_auditorium',
    venue: 'Dr. APJ Abdul Kalam Grand Auditorium',
    event_date: '2026-10-15',
    start_time: '09:30',
    end_time: '13:00',
    registration_deadline: '2026-10-13T23:59:59Z',
    maximum_participants: 35,
    current_participants: 32,
    status: 'open',
    event_image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1000&q=80',
    coordinator_name: 'Meera Nambiar',
    coordinator_contact: '+91 99012 34567',
    coordinator_email: 'dance.colorido@university.edu'
  },
  // 5. Dance - Group
  {
    event_id: 'evt_cul_05',
    event_name: 'Dance — Group Choreography Showcase',
    category: 'cultural',
    sub_category: 'group',
    description: 'Synchronized high-energy formations, storytelling, and kinetic power. College dance crews battle for the ultimate COLORIDO Golden Trophy.',
    rules: [
      'Team size: 6 to 20 members',
      'Time limit: 8 to 10 minutes including intro',
      'Themes can range from urban hip-hop to folk/contemporary fusion',
      'Dangerous stunts or fire strictly prohibited'
    ],
    eligibility: 'College dance crews and registered cultural clubs',
    participation_type: 'team',
    team_size_min: 6,
    team_size_max: 20,
    registration_fee: 1000,
    venue_id: 'v_auditorium',
    venue: 'Dr. APJ Abdul Kalam Grand Auditorium',
    event_date: '2026-10-16',
    start_time: '14:00',
    end_time: '18:00',
    registration_deadline: '2026-10-14T18:00:00Z',
    maximum_participants: 20,
    current_participants: 18,
    status: 'open',
    event_image: 'https://images.unsplash.com/photo-1547153760-18fc86324498?auto=format&fit=crop&w=1000&q=80',
    coordinator_name: 'Karthik Sunder',
    coordinator_contact: '+91 98450 11928',
    coordinator_email: 'danceteam.colorido@university.edu'
  },
  // 6. Choreoday - Theme Based
  {
    event_id: 'evt_cul_06',
    event_name: 'Choreoday — Theme Based Mega Production',
    category: 'cultural',
    sub_category: 'group',
    description: 'The flagship mega-dance theatrical event of COLORIDO 2K26. Elaborate synchronized costumes, dramatic lighting cues, and compelling social or mythological narratives.',
    rules: [
      'Team size: 12 to 30 members',
      'Time limit: 12 to 15 minutes',
      'Mandatory theme statement submission 24h prior',
      'Lighting script must be handed to technical director during rehearsal'
    ],
    eligibility: 'Premier university theatrical and dance societies',
    participation_type: 'team',
    team_size_min: 12,
    team_size_max: 30,
    registration_fee: 1500,
    venue_id: 'v_amphitheatre',
    venue: 'Open Air Amphitheatre',
    event_date: '2026-10-17',
    start_time: '18:30',
    end_time: '22:30',
    registration_deadline: '2026-10-14T23:59:59Z',
    maximum_participants: 12,
    current_participants: 10,
    status: 'open',
    event_image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80',
    coordinator_name: 'Dr. Shalini Verghese',
    coordinator_contact: '+91 99166 77881',
    coordinator_email: 'choreoday.colorido@university.edu'
  },
  // 7. Dramatics
  {
    event_id: 'evt_cul_07',
    event_name: 'Dramatics — Street Play & One-Act Theatre',
    category: 'cultural',
    sub_category: 'group',
    description: 'Vibrant street theater (Nukkad Natak) and stage drama tackling resonant social themes, satire, and human drama with booming voices and rhythmic dhol beats.',
    rules: [
      'Team size: 6 to 18 members',
      'Time limit: 12 minutes for Nukkad Natak / 15 minutes for Stage Play',
      'Acoustic instruments and live vocals preferred for street plays',
      'Script censorship review required before finals'
    ],
    eligibility: 'College theater clubs and drama societies',
    participation_type: 'team',
    team_size_min: 6,
    team_size_max: 18,
    registration_fee: 600,
    venue_id: 'v_amphitheatre',
    venue: 'Open Air Amphitheatre',
    event_date: '2026-10-16',
    start_time: '10:00',
    end_time: '13:30',
    registration_deadline: '2026-10-14T12:00:00Z',
    maximum_participants: 18,
    current_participants: 15,
    status: 'open',
    event_image: 'https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?auto=format&fit=crop&w=1000&q=80',
    coordinator_name: 'Abhishek Banerjee',
    coordinator_contact: '+91 98860 33419',
    coordinator_email: 'dramatics.colorido@university.edu'
  },
  // 8. Fashion Show
  {
    event_id: 'evt_cul_08',
    event_name: 'Fashion Show — Haute Couture “Future Horizons”',
    category: 'cultural',
    sub_category: 'group',
    description: 'A glamorous runway presentation celebrating cutting-edge sustainable fabrics, avant-garde silhouettes, and theatrical walk styling.',
    rules: [
      'Team size: 10 to 18 models and stylists',
      'Time limit: 10 minutes total ramp time',
      'Theme: Future Horizons / Sustainable Futurism',
      'High-res ramp music track and voiceover script mandatory'
    ],
    eligibility: 'College fashion teams and design institute students',
    participation_type: 'team',
    team_size_min: 10,
    team_size_max: 18,
    registration_fee: 1200,
    venue_id: 'v_auditorium',
    venue: 'Dr. APJ Abdul Kalam Grand Auditorium',
    event_date: '2026-10-17',
    start_time: '14:00',
    end_time: '17:30',
    registration_deadline: '2026-10-15T12:00:00Z',
    maximum_participants: 14,
    current_participants: 12,
    status: 'open',
    event_image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1000&q=80',
    coordinator_name: 'Natasha Singhania',
    coordinator_contact: '+91 97311 00293',
    coordinator_email: 'fashion.colorido@university.edu'
  },
  // 9. Tekraft Events
  {
    event_id: 'evt_cul_09',
    event_name: 'Tekraft Events — Creative Digital & Media Fusion',
    category: 'cultural',
    sub_category: 'general',
    description: 'Where culture intertwines with technology: Generative AI art, live VJ visual sets, digital music production, and interactive projection mapping hacks.',
    rules: [
      'Participation: Solo or Duo (1-2 members)',
      'Submission of working prototype + live 5-minute demo',
      'Original assets or properly credited open-source libraries required',
      'Scored on aesthetics, technical depth, and presentation'
    ],
    eligibility: 'Engineering, Arts & Design undergraduates',
    participation_type: 'individual',
    team_size_min: 1,
    team_size_max: 2,
    registration_fee: 300,
    venue_id: 'v_seminar_complex',
    venue: 'Vikram Sarabhai Seminar Complex',
    event_date: '2026-10-16',
    start_time: '10:00',
    end_time: '13:00',
    registration_deadline: '2026-10-14T23:59:59Z',
    maximum_participants: 30,
    current_participants: 22,
    status: 'open',
    event_image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=80',
    coordinator_name: 'Pranav Chordia',
    coordinator_contact: '+91 98412 55910',
    coordinator_email: 'tekraft.colorido@university.edu'
  },
  // 10. Literary
  {
    event_id: 'evt_cul_10',
    event_name: 'Literary — Parliamentary Debate & Slam Poetry',
    category: 'cultural',
    sub_category: 'general',
    description: 'Intellectual sparring of the highest order. British Parliamentary debate rounds alongside poignant spoken-word slam poetry on contemporary cultural dilemmas.',
    rules: [
      'Debate: 2 members per team / Slam Poetry: Individual',
      'Preparation time for debate motions: 15 minutes',
      'Slam Poetry time limit: 3 minutes 30 seconds',
      'Zero tolerance for hate speech or ad hominem remarks'
    ],
    eligibility: 'College literary debaters and writers',
    participation_type: 'individual',
    team_size_min: 1,
    team_size_max: 2,
    registration_fee: 200,
    venue_id: 'v_seminar_complex',
    venue: 'Vikram Sarabhai Seminar Complex',
    event_date: '2026-10-15',
    start_time: '14:00',
    end_time: '17:00',
    registration_deadline: '2026-10-13T23:59:59Z',
    maximum_participants: 40,
    current_participants: 36,
    status: 'open',
    event_image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1000&q=80',
    coordinator_name: 'Tanvi Ranganathan',
    coordinator_contact: '+91 99801 44521',
    coordinator_email: 'literary.colorido@university.edu'
  },

  // SPORTS - BOYS (11-13)
  {
    event_id: 'evt_spt_b_11',
    event_name: 'Basketball Championship — Boys',
    category: 'sports',
    sub_category: 'boys',
    description: 'Full-court collegiate championship following official FIBA rules. Fast breaks, alley-oops, and perimeter defense in a knockout-to-finals tournament bracket.',
    rules: [
      'Squad size: 5 on court + up to 5 rolling substitutes (10 max)',
      'Match duration: 4 quarters of 8 minutes stop-clock',
      'FIBA regulation rules apply; qualified national referees officiate',
      'Matching numbered team jerseys mandatory'
    ],
    eligibility: 'Bonafide male collegiate students with fitness clearance',
    participation_type: 'team',
    team_size_min: 5,
    team_size_max: 10,
    registration_fee: 1000,
    venue_id: 'v_stadium',
    venue: 'University Main Stadium Court A',
    event_date: '2026-10-15',
    start_time: '08:30',
    end_time: '17:30',
    registration_deadline: '2026-10-13T18:00:00Z',
    maximum_participants: 16,
    current_participants: 16,
    status: 'closed',
    event_image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1000&q=80',
    coordinator_name: 'Coach Rajendra Prasad',
    coordinator_contact: '+91 94481 00213',
    coordinator_email: 'basketball.boys@university.edu'
  },
  {
    event_id: 'evt_spt_b_12',
    event_name: 'Volleyball Championship — Boys',
    category: 'sports',
    sub_category: 'boys',
    description: 'Electrifying spikes, monster blocks, and diving digs. Knockout tournament played on international-spec outdoor floodlit courts.',
    rules: [
      'Squad size: 6 on court + 4 substitutes (10 max)',
      'Best of 3 sets of 25 points; Finals best of 5 sets',
      'Standard FIVB rotation and substitution rules enforced',
      'Teams must report 20 minutes before match time'
    ],
    eligibility: 'College male volleyball teams',
    participation_type: 'team',
    team_size_min: 6,
    team_size_max: 10,
    registration_fee: 800,
    venue_id: 'v_stadium',
    venue: 'University Main Stadium Volleyball Arena',
    event_date: '2026-10-16',
    start_time: '08:30',
    end_time: '16:00',
    registration_deadline: '2026-10-14T18:00:00Z',
    maximum_participants: 16,
    current_participants: 14,
    status: 'open',
    event_image: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?auto=format&fit=crop&w=1000&q=80',
    coordinator_name: 'Suresh Goud',
    coordinator_contact: '+91 93421 77281',
    coordinator_email: 'volleyball.boys@university.edu'
  },
  {
    event_id: 'evt_spt_b_13',
    event_name: 'Table Tennis Championship — Boys (Singles & Doubles)',
    category: 'sports',
    sub_category: 'boys',
    description: 'Lightning fast top-spin rallies, defensive chops, and tactical smashes on ITTF approved Stiga tables with 40+ plastic celluloid balls.',
    rules: [
      'Singles & Doubles categories',
      'Matches are best of 5 games up to 11 points (deuce at 10-10)',
      'ITTF approved rubber and rackets mandatory',
      'White apparel not permitted due to white ball contrast'
    ],
    eligibility: 'Male college students',
    participation_type: 'individual',
    team_size_min: 1,
    team_size_max: 2,
    registration_fee: 250,
    venue_id: 'v_sports_complex',
    venue: 'Major Dhyan Chand Indoor Sports Arena',
    event_date: '2026-10-15',
    start_time: '10:00',
    end_time: '16:00',
    registration_deadline: '2026-10-13T23:59:59Z',
    maximum_participants: 32,
    current_participants: 29,
    status: 'open',
    event_image: 'https://images.unsplash.com/photo-1534158914592-062992fbe900?auto=format&fit=crop&w=1000&q=80',
    coordinator_name: 'Manoj Varma',
    coordinator_contact: '+91 97400 33812',
    coordinator_email: 'tabletennis.boys@university.edu'
  },

  // SPORTS - GIRLS (14-16)
  {
    event_id: 'evt_spt_g_14',
    event_name: 'Throwball Championship — Girls',
    category: 'sports',
    sub_category: 'girls',
    description: 'Dynamic rapid-fire team sport requiring razor-sharp reflexes, team coordination, and strategic catch-and-release over the 2.2m net.',
    rules: [
      'Squad: 7 active players + 5 substitutes (12 max)',
      'Best of 3 sets of 25 points each',
      'Ball must be caught with both hands and released within 3 seconds',
      'No body-touch or ball dribble permitted'
    ],
    eligibility: 'Bonafide female collegiate teams',
    participation_type: 'team',
    team_size_min: 7,
    team_size_max: 12,
    registration_fee: 800,
    venue_id: 'v_stadium',
    venue: 'University Main Stadium Court B',
    event_date: '2026-10-15',
    start_time: '09:00',
    end_time: '16:00',
    registration_deadline: '2026-10-13T18:00:00Z',
    maximum_participants: 16,
    current_participants: 12,
    status: 'open',
    event_image: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&w=1000&q=80',
    coordinator_name: 'Kavitha Nair',
    coordinator_contact: '+91 96112 44901',
    coordinator_email: 'throwball.girls@university.edu'
  },
  {
    event_id: 'evt_spt_g_15',
    event_name: 'Tennikoit Championship — Girls (Singles & Doubles)',
    category: 'sports',
    sub_category: 'girls',
    description: 'High-intensity ring tennis played across a standard badminton height net. Demands swift lateral court footwork and deceptive spin catches.',
    rules: [
      'Singles and Doubles matches',
      'Best of 3 sets of 21 points',
      'Ring must be caught cleanly with one hand only',
      'Immediate single-motion return mandatory without hesitation'
    ],
    eligibility: 'Female college students',
    participation_type: 'individual',
    team_size_min: 1,
    team_size_max: 2,
    registration_fee: 250,
    venue_id: 'v_sports_complex',
    venue: 'Major Dhyan Chand Indoor Court 2',
    event_date: '2026-10-16',
    start_time: '09:30',
    end_time: '15:30',
    registration_deadline: '2026-10-14T18:00:00Z',
    maximum_participants: 24,
    current_participants: 20,
    status: 'open',
    event_image: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?auto=format&fit=crop&w=1000&q=80',
    coordinator_name: 'Deepa Balakrishnan',
    coordinator_contact: '+91 98801 66290',
    coordinator_email: 'tennikoit.girls@university.edu'
  },
  {
    event_id: 'evt_spt_g_16',
    event_name: 'Table Tennis Championship — Girls (Singles & Doubles)',
    category: 'sports',
    sub_category: 'girls',
    description: 'Competitive table tennis showcasing high-speed rallies, spin mastery, and precision placement on international-grade tables.',
    rules: [
      'Singles and Doubles knockouts',
      'Best of 5 games of 11 points',
      'Standard ITTF equipment regulations enforced',
      'Warm-up time strictly 2 minutes per match'
    ],
    eligibility: 'Bonafide female college students',
    participation_type: 'individual',
    team_size_min: 1,
    team_size_max: 2,
    registration_fee: 250,
    venue_id: 'v_sports_complex',
    venue: 'Major Dhyan Chand Indoor Sports Arena',
    event_date: '2026-10-17',
    start_time: '09:30',
    end_time: '15:00',
    registration_deadline: '2026-10-15T18:00:00Z',
    maximum_participants: 32,
    current_participants: 26,
    status: 'open',
    event_image: 'https://images.unsplash.com/photo-1511067007772-9da29974e9b9?auto=format&fit=crop&w=1000&q=80',
    coordinator_name: 'Pooja Hegde',
    coordinator_contact: '+91 99450 88201',
    coordinator_email: 'tabletennis.girls@university.edu'
  }
];

export const INITIAL_SCHEDULES: ScheduleItem[] = [
  {
    id: 'sch_01',
    event_id: 'evt_spt_b_11',
    day_number: 1,
    schedule_date: '2026-10-15',
    start_time: '08:30',
    end_time: '12:30',
    venue_id: 'v_stadium',
    venue_name: 'University Main Stadium Court A',
    round_name: 'Round of 16 & Quarter Finals',
    status: 'scheduled'
  },
  {
    id: 'sch_02',
    event_id: 'evt_spt_g_14',
    day_number: 1,
    schedule_date: '2026-10-15',
    start_time: '09:00',
    end_time: '13:00',
    venue_id: 'v_stadium',
    venue_name: 'University Main Stadium Court B',
    round_name: 'League Knockout Stage',
    status: 'scheduled'
  },
  {
    id: 'sch_03',
    event_id: 'evt_cul_04',
    day_number: 1,
    schedule_date: '2026-10-15',
    start_time: '09:30',
    end_time: '13:00',
    venue_id: 'v_auditorium',
    venue_name: 'Dr. APJ Abdul Kalam Grand Auditorium',
    round_name: 'Preliminary Round',
    status: 'scheduled'
  },
  {
    id: 'sch_04',
    event_id: 'evt_cul_01',
    day_number: 1,
    schedule_date: '2026-10-15',
    start_time: '10:00',
    end_time: '13:00',
    venue_id: 'v_arts_studio',
    venue_name: 'Raja Ravi Varma Fine Arts Pavilion',
    round_name: 'Main Live Competition',
    status: 'scheduled'
  },
  {
    id: 'sch_05',
    event_id: 'evt_spt_b_13',
    day_number: 1,
    schedule_date: '2026-10-15',
    start_time: '10:00',
    end_time: '13:00',
    venue_id: 'v_sports_complex',
    venue_name: 'Indoor Sports Arena',
    round_name: 'Boys Singles Round of 32',
    status: 'scheduled'
  },
  {
    id: 'sch_06',
    event_id: 'evt_cul_02',
    day_number: 1,
    schedule_date: '2026-10-15',
    start_time: '14:00',
    end_time: '17:30',
    venue_id: 'v_auditorium',
    venue_name: 'Dr. APJ Abdul Kalam Grand Auditorium',
    round_name: 'Solo Vocals & Instrumentals Finals',
    status: 'scheduled'
  },
  {
    id: 'sch_07',
    event_id: 'evt_cul_10',
    day_number: 1,
    schedule_date: '2026-10-15',
    start_time: '14:00',
    end_time: '17:00',
    venue_id: 'v_seminar_complex',
    venue_name: 'Vikram Sarabhai Seminar Complex',
    round_name: 'Parliamentary Debate Round 1',
    status: 'scheduled'
  },
  {
    id: 'sch_08',
    event_id: 'evt_spt_b_11',
    day_number: 1,
    schedule_date: '2026-10-15',
    start_time: '14:30',
    end_time: '17:30',
    venue_id: 'v_stadium',
    venue_name: 'University Main Stadium Court A',
    round_name: 'Semi Finals & Grand Finale',
    status: 'scheduled'
  },
  {
    id: 'sch_09',
    event_id: 'evt_spt_b_12',
    day_number: 2,
    schedule_date: '2026-10-16',
    start_time: '08:30',
    end_time: '12:30',
    venue_id: 'v_stadium',
    venue_name: 'University Main Stadium Volleyball Arena',
    round_name: 'Boys Volleyball Knockout Round',
    status: 'scheduled'
  },
  {
    id: 'sch_10',
    event_id: 'evt_spt_g_15',
    day_number: 2,
    schedule_date: '2026-10-16',
    start_time: '09:30',
    end_time: '13:00',
    venue_id: 'v_sports_complex',
    venue_name: 'Indoor Sports Arena Court 2',
    round_name: 'Tennikoit Singles & Doubles Pre-quarters',
    status: 'scheduled'
  },
  {
    id: 'sch_11',
    event_id: 'evt_cul_07',
    day_number: 2,
    schedule_date: '2026-10-16',
    start_time: '10:00',
    end_time: '13:30',
    venue_id: 'v_amphitheatre',
    venue_name: 'Open Air Amphitheatre',
    round_name: 'Street Play (Nukkad Natak) Showcase',
    status: 'scheduled'
  },
  {
    id: 'sch_12',
    event_id: 'evt_cul_09',
    day_number: 2,
    schedule_date: '2026-10-16',
    start_time: '10:00',
    end_time: '13:00',
    venue_id: 'v_seminar_complex',
    venue_name: 'Vikram Sarabhai Seminar Complex',
    round_name: 'Creative Tech & Digital Exhibition',
    status: 'scheduled'
  },
  {
    id: 'sch_13',
    event_id: 'evt_cul_05',
    day_number: 2,
    schedule_date: '2026-10-16',
    start_time: '14:00',
    end_time: '18:00',
    venue_id: 'v_auditorium',
    venue_name: 'Dr. APJ Abdul Kalam Grand Auditorium',
    round_name: 'Group Dance Choreography Finals',
    status: 'scheduled'
  },
  {
    id: 'sch_14',
    event_id: 'evt_spt_b_12',
    day_number: 2,
    schedule_date: '2026-10-16',
    start_time: '14:00',
    end_time: '16:30',
    venue_id: 'v_stadium',
    venue_name: 'University Main Stadium Volleyball Arena',
    round_name: 'Volleyball Championship Finals',
    status: 'scheduled'
  },
  {
    id: 'sch_15',
    event_id: 'evt_cul_03',
    day_number: 2,
    schedule_date: '2026-10-16',
    start_time: '18:00',
    end_time: '22:00',
    venue_id: 'v_amphitheatre',
    venue_name: 'Open Air Amphitheatre',
    round_name: 'Battle of the Bands Grand Concert',
    status: 'scheduled'
  },
  {
    id: 'sch_16',
    event_id: 'evt_spt_g_16',
    day_number: 3,
    schedule_date: '2026-10-17',
    start_time: '09:30',
    end_time: '13:00',
    venue_id: 'v_sports_complex',
    venue_name: 'Indoor Sports Arena',
    round_name: 'Girls Table Tennis Pre-quarters & Quarters',
    status: 'scheduled'
  },
  {
    id: 'sch_17',
    event_id: 'evt_cul_08',
    day_number: 3,
    schedule_date: '2026-10-17',
    start_time: '14:00',
    end_time: '17:30',
    venue_id: 'v_auditorium',
    venue_name: 'Dr. APJ Abdul Kalam Grand Auditorium',
    round_name: 'Haute Couture Runway Show',
    status: 'scheduled'
  },
  {
    id: 'sch_18',
    event_id: 'evt_spt_g_16',
    day_number: 3,
    schedule_date: '2026-10-17',
    start_time: '14:00',
    end_time: '16:00',
    venue_id: 'v_sports_complex',
    venue_name: 'Indoor Sports Arena',
    round_name: 'Girls TT Semi Finals & Final Match',
    status: 'scheduled'
  },
  {
    id: 'sch_19',
    event_id: 'evt_cul_06',
    day_number: 3,
    schedule_date: '2026-10-17',
    start_time: '18:30',
    end_time: '22:30',
    venue_id: 'v_amphitheatre',
    venue_name: 'Open Air Amphitheatre',
    round_name: 'Choreoday Mega Dance Production & Award Gala',
    status: 'scheduled'
  }
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann_01',
    title: '🚨 Official Schedule & Reporting Time Notice',
    description: 'All team contingents must report to the Central Registration Desk at Block A minimum 45 minutes before scheduled heat times with original institutional photo IDs.',
    category: 'IMPORTANT',
    priority: 'Urgent',
    is_published: true,
    published_at: '2026-10-14T08:00:00Z',
    author: 'Festival Secretariat',
    pinned: true
  },
  {
    id: 'ann_02',
    title: '🏀 Basketball Boys Championship Draws Released',
    description: 'Knockout fixtures and court allocations for the 16 participating universities have been published. Check fixtures at the sports arena.',
    category: 'SPORTS',
    priority: 'Important',
    is_published: true,
    published_at: '2026-10-14T09:30:00Z',
    author: 'Sports Organizing Committee',
    pinned: false
  },
  {
    id: 'ann_03',
    title: '🎸 Battle of the Bands Soundcheck Timings',
    description: 'Acoustic soundchecks for shortlisted band teams will commence on Day 2 from 07:00 AM to 09:30 AM at Open Air Amphitheatre.',
    category: 'CULTURAL',
    priority: 'Important',
    is_published: true,
    published_at: '2026-10-14T11:00:00Z',
    author: 'Cultural Committee',
    pinned: false
  },
  {
    id: 'ann_04',
    title: '🎨 Fine Arts Live Topic Announcement Protocol',
    description: 'The central theme for Fine Arts Live Canvas will be unsealed in the presence of external judges at exactly 09:45 AM on Day 1.',
    category: 'CULTURAL',
    priority: 'Normal',
    is_published: true,
    published_at: '2026-10-13T16:00:00Z',
    author: 'Arts Club Head',
    pinned: false
  },
  {
    id: 'ann_05',
    title: '🚌 Free Campus Shuttle Services Activated',
    description: 'Electric shuttle buses will ply every 10 minutes between Main Gate, Indoor Arena, Stadium, and North Lake Amphitheatre throughout the festival days.',
    category: 'GENERAL',
    priority: 'Normal',
    is_published: true,
    published_at: '2026-10-13T14:00:00Z',
    author: 'Campus Logistics',
    pinned: false
  },
  {
    id: 'ann_06',
    title: '⚡ Schedule Update: Girls Throwball Match Timings',
    description: 'Due to high registration volume, Match Court B will start 30 minutes earlier at 08:30 AM. Registered team leaders please take note.',
    category: 'SCHEDULE',
    priority: 'Important',
    is_published: true,
    published_at: '2026-10-14T15:00:00Z',
    author: 'Tournament Director',
    pinned: false
  },
  {
    id: 'ann_07',
    title: '🏆 Rolling Trophy Standings System Live',
    description: 'The COLORIDO 2K26 Live Championship Leaderboard is now officially tracking points across all 16 disciplines. First place = 10 pts, Second = 7 pts, Third = 5 pts.',
    category: 'RESULTS',
    priority: 'Important',
    is_published: true,
    published_at: '2026-10-14T17:00:00Z',
    author: 'Scoring Board',
    pinned: true
  },
  {
    id: 'ann_08',
    title: '🎙️ Slam Poetry Finalists Shortlist Out',
    description: 'Top 12 qualifying poets for the final round at Sarabhai Complex have been posted. View your status in the results portal.',
    category: 'RESULTS',
    priority: 'Normal',
    is_published: true,
    published_at: '2026-10-14T18:30:00Z',
    author: 'Literary Society',
    pinned: false
  },
  {
    id: 'ann_09',
    title: '👗 Haute Couture Runway Technical Guidelines',
    description: 'Costume checks and footwear safety inspections for the Fashion Show will be held on Day 3 morning in Green Room 2 & 3.',
    category: 'CULTURAL',
    priority: 'Normal',
    is_published: true,
    published_at: '2026-10-14T19:00:00Z',
    author: 'Fashion Society Coordinator',
    pinned: false
  },
  {
    id: 'ann_10',
    title: '🌧️ Weather Contingency Plan for Outdoor Venues',
    description: 'In case of evening rains, Choreoday and Dramatics will seamlessly shift to the 2,000-seater Multipurpose Covered Arena.',
    category: 'GENERAL',
    priority: 'Normal',
    is_published: true,
    published_at: '2026-10-13T10:00:00Z',
    author: 'Safety & Facilities Team',
    pinned: false
  },
  {
    id: 'ann_11',
    title: '📱 QR Code Check-in Required at Every Gate',
    description: 'Show your Digital Pass QR code on your mobile phone at venue turnstiles for instant contactless verification.',
    category: 'IMPORTANT',
    priority: 'Urgent',
    is_published: true,
    published_at: '2026-10-14T07:00:00Z',
    author: 'Tech Operations Team',
    pinned: true
  },
  {
    id: 'ann_12',
    title: '🏓 Table Tennis Boys Singles Seedings Confirmed',
    description: 'National youth ranked seeds #1 to #4 receive first-round byes in accordance with ITTF tournament bracket protocols.',
    category: 'SPORTS',
    priority: 'Normal',
    is_published: true,
    published_at: '2026-10-13T19:00:00Z',
    author: 'Chief Referee',
    pinned: false
  },
  {
    id: 'ann_13',
    title: '🍕 Food Street & Night Market Openings',
    description: 'Over 40 food stalls featuring regional delicacies and artisanal beverages will stay open till 11:30 PM outside the Amphitheatre.',
    category: 'GENERAL',
    priority: 'Normal',
    is_published: true,
    published_at: '2026-10-13T12:00:00Z',
    author: 'Student Council',
    pinned: false
  },
  {
    id: 'ann_14',
    title: '📜 Instant Digital Certificates Enabled',
    description: 'Verified participants can download digitally signed, QR-verifiable certificates directly from their My Dashboard immediately following result publication.',
    category: 'RESULTS',
    priority: 'Important',
    is_published: true,
    published_at: '2026-10-14T20:00:00Z',
    author: 'Secretariat IT Desk',
    pinned: false
  },
  {
    id: 'ann_15',
    title: '🤝 Special Thanks to Title Sponsor Titan Corp',
    description: 'Titan Corporation has partnered with COLORIDO 2K26 to award luxury chronographs to all 1st place winners!',
    category: 'GENERAL',
    priority: 'Normal',
    is_published: true,
    published_at: '2026-10-13T09:00:00Z',
    author: 'Sponsorship Cell',
    pinned: false
  }
];

export const INITIAL_RESULTS: ResultItem[] = [
  {
    id: 'res_01',
    event_id: 'evt_spt_b_11',
    event_name: 'Basketball Championship — Boys',
    position: '1st Place',
    winner_type: 'Winner',
    participant_name: 'Aryan Nair (Captain)',
    team_name: 'St. Xavier Ballers',
    college: "St. Xavier's College, Mumbai",
    score: '84 - 78',
    points_awarded: 10,
    is_published: true,
    published_at: '2026-10-15T18:00:00Z'
  },
  {
    id: 'res_02',
    event_id: 'evt_spt_b_11',
    event_name: 'Basketball Championship — Boys',
    position: '2nd Place',
    winner_type: 'Runner-up',
    participant_name: 'Devendra Singh (Captain)',
    team_name: 'Loyola Stallions',
    college: 'Loyola College, Chennai',
    score: '78 - 84',
    points_awarded: 7,
    is_published: true,
    published_at: '2026-10-15T18:00:00Z'
  },
  {
    id: 'res_03',
    event_id: 'evt_spt_b_11',
    event_name: 'Basketball Championship — Boys',
    position: '3rd Place',
    winner_type: 'Second Runner-up',
    participant_name: 'Rishi Menon (Captain)',
    team_name: 'BITS Pilani Kings',
    college: 'BITS Pilani',
    score: '72 - 68',
    points_awarded: 5,
    is_published: true,
    published_at: '2026-10-15T18:00:00Z'
  },
  {
    id: 'res_04',
    event_id: 'evt_cul_02',
    event_name: 'Music & Band — Solo (Vocal / Instrumental)',
    position: '1st Place',
    winner_type: 'Winner',
    participant_name: 'Dhruv Ratnam',
    college: 'National Institute of Design, Ahmedabad',
    score: '97.5 / 100',
    points_awarded: 10,
    is_published: true,
    published_at: '2026-10-15T18:30:00Z'
  },
  {
    id: 'res_05',
    event_id: 'evt_cul_02',
    event_name: 'Music & Band — Solo (Vocal / Instrumental)',
    position: '2nd Place',
    winner_type: 'Runner-up',
    participant_name: 'Samyuktha Iyer',
    college: 'Stella Maris College, Chennai',
    score: '94.0 / 100',
    points_awarded: 7,
    is_published: true,
    published_at: '2026-10-15T18:30:00Z'
  },
  {
    id: 'res_06',
    event_id: 'evt_cul_02',
    event_name: 'Music & Band — Solo (Vocal / Instrumental)',
    position: '3rd Place',
    winner_type: 'Second Runner-up',
    participant_name: 'Tenzin Norbu',
    college: 'Delhi University, Hindu College',
    score: '91.8 / 100',
    points_awarded: 5,
    is_published: true,
    published_at: '2026-10-15T18:30:00Z'
  },
  {
    id: 'res_07',
    event_id: 'evt_cul_04',
    event_name: 'Dance — Solo (Classical / Freestyle)',
    position: '1st Place',
    winner_type: 'Winner',
    participant_name: 'Sneha Ramamurthy',
    college: 'Madras Christian College, Chennai',
    score: '98.0 / 100',
    points_awarded: 10,
    is_published: true,
    published_at: '2026-10-15T14:30:00Z'
  },
  {
    id: 'res_08',
    event_id: 'evt_cul_04',
    event_name: 'Dance — Solo (Classical / Freestyle)',
    position: '2nd Place',
    winner_type: 'Runner-up',
    participant_name: 'Anandita Roy',
    college: 'Jadavpur University, Kolkata',
    score: '96.2 / 100',
    points_awarded: 7,
    is_published: true,
    published_at: '2026-10-15T14:30:00Z'
  },
  {
    id: 'res_09',
    event_id: 'evt_cul_04',
    event_name: 'Dance — Solo (Classical / Freestyle)',
    position: '3rd Place',
    winner_type: 'Second Runner-up',
    participant_name: 'Farhan Qureshi',
    college: 'Jamia Millia Islamia, New Delhi',
    score: '93.5 / 100',
    points_awarded: 5,
    is_published: true,
    published_at: '2026-10-15T14:30:00Z'
  },
  {
    id: 'res_10',
    event_id: 'evt_spt_b_13',
    event_name: 'Table Tennis Championship — Boys',
    position: '1st Place',
    winner_type: 'Winner',
    participant_name: 'Siddharth Kaushik',
    college: 'PSG College of Technology, Coimbatore',
    score: '3 - 1 (11-9, 11-8, 9-11, 11-7)',
    points_awarded: 10,
    is_published: true,
    published_at: '2026-10-15T17:00:00Z'
  },
  {
    id: 'res_11',
    event_id: 'evt_spt_b_13',
    event_name: 'Table Tennis Championship — Boys',
    position: '2nd Place',
    winner_type: 'Runner-up',
    participant_name: 'Karan Singhal',
    college: 'IIT Madras',
    score: '1 - 3 (9-11, 8-11, 11-9, 7-11)',
    points_awarded: 7,
    is_published: true,
    published_at: '2026-10-15T17:00:00Z'
  },
  {
    id: 'res_12',
    event_id: 'evt_spt_b_13',
    event_name: 'Table Tennis Championship — Boys',
    position: '3rd Place',
    winner_type: 'Second Runner-up',
    participant_name: 'Varun Teja',
    college: 'Osmania University, Hyderabad',
    score: '3 - 2 (12-10 in 5th)',
    points_awarded: 5,
    is_published: true,
    published_at: '2026-10-15T17:00:00Z'
  },
  {
    id: 'res_13',
    event_id: 'evt_cul_01',
    event_name: 'Fine Arts Exhibition & Live Canvas',
    position: '1st Place',
    winner_type: 'Winner',
    participant_name: 'Priyanka Sen',
    college: 'College of Fine Arts, Bengaluru',
    score: '99.0 / 100',
    points_awarded: 10,
    is_published: true,
    published_at: '2026-10-15T14:00:00Z'
  },
  {
    id: 'res_14',
    event_id: 'evt_cul_01',
    event_name: 'Fine Arts Exhibition & Live Canvas',
    position: '2nd Place',
    winner_type: 'Runner-up',
    participant_name: 'Aditya Joshi',
    college: 'Sir J.J. Institute of Applied Art, Mumbai',
    score: '95.5 / 100',
    points_awarded: 7,
    is_published: true,
    published_at: '2026-10-15T14:00:00Z'
  },
  {
    id: 'res_15',
    event_id: 'evt_cul_01',
    event_name: 'Fine Arts Exhibition & Live Canvas',
    position: '3rd Place',
    winner_type: 'Second Runner-up',
    participant_name: 'Meenakshi Sundaram',
    college: 'Government College of Fine Arts, Chennai',
    score: '92.0 / 100',
    points_awarded: 5,
    is_published: true,
    published_at: '2026-10-15T14:00:00Z'
  }
];

export const INITIAL_LEADERBOARD: LeaderboardEntry[] = [
  {
    id: 'lead_01',
    college_name: "St. Xavier's College, Mumbai",
    cultural_points: 10,
    sports_points: 10,
    total_points: 20,
    gold_count: 2,
    silver_count: 0,
    bronze_count: 0,
    rank: 1
  },
  {
    id: 'lead_02',
    college_name: 'Loyola College, Chennai',
    cultural_points: 7,
    sports_points: 7,
    total_points: 14,
    gold_count: 0,
    silver_count: 2,
    bronze_count: 0,
    rank: 2
  },
  {
    id: 'lead_03',
    college_name: 'National Institute of Design, Ahmedabad',
    cultural_points: 10,
    sports_points: 0,
    total_points: 10,
    gold_count: 1,
    silver_count: 0,
    bronze_count: 0,
    rank: 3
  },
  {
    id: 'lead_04',
    college_name: 'PSG College of Technology, Coimbatore',
    cultural_points: 0,
    sports_points: 10,
    total_points: 10,
    gold_count: 1,
    silver_count: 0,
    bronze_count: 0,
    rank: 4
  },
  {
    id: 'lead_05',
    college_name: 'Madras Christian College, Chennai',
    cultural_points: 10,
    sports_points: 0,
    total_points: 10,
    gold_count: 1,
    silver_count: 0,
    bronze_count: 0,
    rank: 5
  },
  {
    id: 'lead_06',
    college_name: 'College of Fine Arts, Bengaluru',
    cultural_points: 10,
    sports_points: 0,
    total_points: 10,
    gold_count: 1,
    silver_count: 0,
    bronze_count: 0,
    rank: 6
  },
  {
    id: 'lead_07',
    college_name: 'IIT Madras',
    cultural_points: 0,
    sports_points: 7,
    total_points: 7,
    gold_count: 0,
    silver_count: 1,
    bronze_count: 0,
    rank: 7
  },
  {
    id: 'lead_08',
    college_name: 'Stella Maris College, Chennai',
    cultural_points: 7,
    sports_points: 0,
    total_points: 7,
    gold_count: 0,
    silver_count: 1,
    bronze_count: 0,
    rank: 8
  },
  {
    id: 'lead_09',
    college_name: 'BITS Pilani',
    cultural_points: 0,
    sports_points: 5,
    total_points: 5,
    gold_count: 0,
    silver_count: 0,
    bronze_count: 1,
    rank: 9
  },
  {
    id: 'lead_10',
    college_name: 'Jadavpur University, Kolkata',
    cultural_points: 7,
    sports_points: 0,
    total_points: 7,
    gold_count: 0,
    silver_count: 1,
    bronze_count: 0,
    rank: 10
  }
];

export const INITIAL_SPONSORS: Sponsor[] = [
  {
    id: 'sp_01',
    name: 'Titanium Edge Tech',
    category: 'TITLE SPONSOR',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80',
    description: 'Global cloud computing and developer ecosystem pioneer presenting COLORIDO 2K26.',
    website_url: 'https://titaniumedge.tech',
    display_order: 1
  },
  {
    id: 'sp_02',
    name: 'RedBull Energy',
    category: 'GOLD SPONSOR',
    logo_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=300&q=80',
    description: 'Powering athletes, dancers, and creative performers with non-stop adrenaline.',
    website_url: 'https://redbull.com',
    display_order: 2
  },
  {
    id: 'sp_03',
    name: 'Decathlon Sports',
    category: 'GOLD SPONSOR',
    logo_url: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=300&q=80',
    description: 'Official sports gear and equipment partner for all boys and girls championships.',
    website_url: 'https://decathlon.in',
    display_order: 3
  },
  {
    id: 'sp_04',
    name: 'AudioTechnica Pro',
    category: 'SILVER SPONSOR',
    logo_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=300&q=80',
    description: 'Pioneering stage monitors, studio mics, and live audio rigs for Battle of the Bands.',
    website_url: 'https://audio-technica.com',
    display_order: 4
  },
  {
    id: 'sp_05',
    name: 'Campus Chronicle',
    category: 'MEDIA PARTNER',
    logo_url: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=300&q=80',
    description: 'Exclusive live stream broadcasts, backstage interviews, and digital press coverage.',
    website_url: 'https://campuschronicle.org',
    display_order: 5
  },
  {
    id: 'sp_06',
    name: 'Spotify Student',
    category: 'EVENT PARTNER',
    logo_url: 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?auto=format&fit=crop&w=300&q=80',
    description: 'Official festival playlist partner streaming student indie artist tracks nationwide.',
    website_url: 'https://spotify.com',
    display_order: 6
  }
];

export const INITIAL_GALLERY: GalleryItem[] = [
  {
    id: 'gal_01',
    title: 'Neon Night Opening Spectacle',
    image_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
    category: 'CAMPUS',
    tags: ['Opening Ceremony', 'Amphitheatre', 'Lights'],
    featured: true,
    caption: 'Over 5,000 university students gather at the central amphitheatre for the opening ceremony laser launch.'
  },
  {
    id: 'gal_02',
    title: 'Electric Guitar Shredding Finals',
    image_url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=1200&q=80',
    category: 'PERFORMANCES',
    tags: ['Battle of the Bands', 'Rock', 'Live Music'],
    featured: true,
    caption: "The lead guitarist from St. Xavier's rock crew tearing down the stage during Battle of the Bands."
  },
  {
    id: 'gal_03',
    title: 'Clutch Buzzer Beater Dunk',
    image_url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=80',
    category: 'SPORTS',
    tags: ['Basketball', 'Boys Championship', 'Stadium'],
    featured: true,
    caption: 'Unbelievable fourth-quarter fast break during the Boys Basketball championship match.'
  },
  {
    id: 'gal_04',
    title: 'Contemporary Duet in Flight',
    image_url: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1200&q=80',
    category: 'CULTURAL',
    tags: ['Dance', 'Solo', 'Contemporary'],
    featured: true,
    caption: 'Breathtaking mid-air synchronization during the Solo & Duet contemporary dance preliminary.'
  },
  {
    id: 'gal_05',
    title: 'Acrylic Impressions on Live Canvas',
    image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80',
    category: 'CULTURAL',
    tags: ['Fine Arts', 'Canvas', 'Exhibition'],
    featured: false,
    caption: 'A participant fine-tuning vibrant brush strokes during the 3-hour live fine arts session.'
  },
  {
    id: 'gal_06',
    title: 'Haute Couture Futuristic Ramp',
    image_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=80',
    category: 'HIGHLIGHTS',
    tags: ['Fashion Show', 'Ramp Walk', 'Future Horizons'],
    featured: true,
    caption: 'Stunning sustainable textile designs exhibited by the National Institute of Fashion Technology team.'
  },
  {
    id: 'gal_07',
    title: 'Dramatics Street Play Circle',
    image_url: 'https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?auto=format&fit=crop&w=1200&q=80',
    category: 'CULTURAL',
    tags: ['Dramatics', 'Nukkad Natak', 'Theatre'],
    featured: false,
    caption: 'Rousing theatrical energy as drama students address societal themes through Nukkad Natak.'
  },
  {
    id: 'gal_08',
    title: 'High Stakes Table Tennis Rally',
    image_url: 'https://images.unsplash.com/photo-1534158914592-062992fbe900?auto=format&fit=crop&w=1200&q=80',
    category: 'SPORTS',
    tags: ['Table Tennis', 'Boys', 'Singles'],
    featured: false,
    caption: 'Speed and spin mastery in the Boys Table Tennis finals at the indoor stadium.'
  },
  {
    id: 'gal_09',
    title: 'Girls Volleyball Block at the Net',
    image_url: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?auto=format&fit=crop&w=1200&q=80',
    category: 'SPORTS',
    tags: ['Volleyball', 'Defense', 'Championship'],
    featured: true,
    caption: 'A double wall block denial at the decisive match point during the intense second set.'
  },
  {
    id: 'gal_10',
    title: 'Student Crowds Cheering in the Stands',
    image_url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80',
    category: 'CAMPUS',
    tags: ['Crowd', 'Spirit', 'University'],
    featured: true,
    caption: 'Electrifying atmosphere with flags, banners, and college chants echoing across the stadium arena.'
  }
];

export const INITIAL_PARTICIPANTS: Participant[] = [
  {
    id: 'usr_part_01',
    user_id: 'usr_part_01',
    full_name: 'Aarav Sharma',
    email: 'aarav.sharma@xavier.edu',
    phone: '+91 98210 11223',
    college: "St. Xavier's College, Mumbai",
    department: 'Computer Science',
    year: '3rd Year',
    gender: 'Male',
    city: 'Mumbai',
    state: 'Maharashtra'
  },
  {
    id: 'usr_part_02',
    user_id: 'usr_part_02',
    full_name: 'Diya Krishnan',
    email: 'diya.krishnan@loyola.edu',
    phone: '+91 98401 22334',
    college: 'Loyola College, Chennai',
    department: 'Visual Arts',
    year: '2nd Year',
    gender: 'Female',
    city: 'Chennai',
    state: 'Tamil Nadu'
  },
  {
    id: 'usr_part_03',
    user_id: 'usr_part_03',
    full_name: 'Kabir Mehta',
    email: 'kabir.mehta@bits.edu',
    phone: '+91 97112 33445',
    college: 'BITS Pilani',
    department: 'Mechanical Engineering',
    year: '4th Year',
    gender: 'Male',
    city: 'Pilani',
    state: 'Rajasthan'
  },
  {
    id: 'usr_part_04',
    user_id: 'usr_part_04',
    full_name: 'Ananya Deshmukh',
    email: 'ananya.d@iitm.ac.in',
    phone: '+91 94451 44556',
    college: 'IIT Madras',
    department: 'Aerospace Engineering',
    year: '3rd Year',
    gender: 'Female',
    city: 'Chennai',
    state: 'Tamil Nadu'
  },
  {
    id: 'usr_part_05',
    user_id: 'usr_part_05',
    full_name: 'Rohan Sengupta',
    email: 'rohan.sen@jadavpur.edu',
    phone: '+91 98302 55667',
    college: 'Jadavpur University, Kolkata',
    department: 'English Literature',
    year: '2nd Year',
    gender: 'Male',
    city: 'Kolkata',
    state: 'West Bengal'
  },
  {
    id: 'usr_part_06',
    user_id: 'usr_part_06',
    full_name: 'Sneha Ramamurthy',
    email: 'sneha.r@mcc.edu',
    phone: '+91 98409 66778',
    college: 'Madras Christian College, Chennai',
    department: 'Economics',
    year: '3rd Year',
    gender: 'Female',
    city: 'Chennai',
    state: 'Tamil Nadu'
  },
  {
    id: 'usr_part_07',
    user_id: 'usr_part_07',
    full_name: 'Siddharth Kaushik',
    email: 'sid.kaushik@psgtech.edu',
    phone: '+91 97890 77889',
    college: 'PSG College of Technology, Coimbatore',
    department: 'Automobile Engineering',
    year: '4th Year',
    gender: 'Male',
    city: 'Coimbatore',
    state: 'Tamil Nadu'
  },
  {
    id: 'usr_part_08',
    user_id: 'usr_part_08',
    full_name: 'Priyanka Sen',
    email: 'priyanka.sen@bengaluruarts.edu',
    phone: '+91 99001 88990',
    college: 'College of Fine Arts, Bengaluru',
    department: 'Painting & Applied Art',
    year: '3rd Year',
    gender: 'Female',
    city: 'Bengaluru',
    state: 'Karnataka'
  },
  {
    id: 'usr_part_09',
    user_id: 'usr_part_09',
    full_name: 'Dhruv Ratnam',
    email: 'dhruv.r@nid.ac.in',
    phone: '+91 98791 99001',
    college: 'National Institute of Design, Ahmedabad',
    department: 'Communication Design',
    year: '3rd Year',
    gender: 'Male',
    city: 'Ahmedabad',
    state: 'Gujarat'
  },
  {
    id: 'usr_part_10',
    user_id: 'usr_part_10',
    full_name: 'Samyuktha Iyer',
    email: 'samyuktha.i@stellamaris.edu',
    phone: '+91 98412 11224',
    college: 'Stella Maris College, Chennai',
    department: 'Music & Performing Arts',
    year: '2nd Year',
    gender: 'Female',
    city: 'Chennai',
    state: 'Tamil Nadu'
  }
];

// Pre-seeded registrations with 30+ records
export const INITIAL_REGISTRATIONS: Registration[] = [
  {
    id: 'reg_01',
    registration_id: 'COL26-SPT-001001',
    event_id: 'evt_spt_b_11',
    user_id: 'usr_part_01',
    participant_name: 'Aarav Sharma',
    participant_email: 'aarav.sharma@xavier.edu',
    participant_phone: '+91 98210 11223',
    participant_college: "St. Xavier's College, Mumbai",
    participation_type: 'team',
    team_name: 'St. Xavier Ballers',
    team_size: 8,
    emergency_contact_name: 'Sunil Sharma',
    emergency_contact_phone: '+91 98210 99887',
    status: 'checked_in',
    qr_code_data: 'COL26-REG:COL26-SPT-001001|EVT:evt_spt_b_11|NAME:Aarav Sharma|COLLEGE:St. Xavier',
    created_at: '2026-10-01T10:00:00Z'
  },
  {
    id: 'reg_02',
    registration_id: 'COL26-CUL-001002',
    event_id: 'evt_cul_01',
    user_id: 'usr_part_02',
    participant_name: 'Diya Krishnan',
    participant_email: 'diya.krishnan@loyola.edu',
    participant_phone: '+91 98401 22334',
    participant_college: 'Loyola College, Chennai',
    participation_type: 'individual',
    team_size: 1,
    emergency_contact_name: 'P. Krishnan',
    emergency_contact_phone: '+91 98401 88776',
    status: 'confirmed',
    qr_code_data: 'COL26-REG:COL26-CUL-001002|EVT:evt_cul_01|NAME:Diya Krishnan|COLLEGE:Loyola College',
    created_at: '2026-10-02T11:30:00Z'
  },
  {
    id: 'reg_03',
    registration_id: 'COL26-CUL-001003',
    event_id: 'evt_cul_02',
    user_id: 'usr_part_03',
    participant_name: 'Kabir Mehta',
    participant_email: 'kabir.mehta@bits.edu',
    participant_phone: '+91 97112 33445',
    participant_college: 'BITS Pilani',
    participation_type: 'individual',
    team_size: 1,
    emergency_contact_name: 'Rajiv Mehta',
    emergency_contact_phone: '+91 97112 77665',
    status: 'confirmed',
    qr_code_data: 'COL26-REG:COL26-CUL-001003|EVT:evt_cul_02|NAME:Kabir Mehta|COLLEGE:BITS Pilani',
    created_at: '2026-10-03T14:15:00Z'
  },
  {
    id: 'reg_04',
    registration_id: 'COL26-SPT-001004',
    event_id: 'evt_spt_g_14',
    user_id: 'usr_part_04',
    participant_name: 'Ananya Deshmukh',
    participant_email: 'ananya.d@iitm.ac.in',
    participant_phone: '+91 94451 44556',
    participant_college: 'IIT Madras',
    participation_type: 'team',
    team_name: 'IITM Phoenix',
    team_size: 9,
    emergency_contact_name: 'V. Deshmukh',
    emergency_contact_phone: '+91 94451 66554',
    status: 'checked_in',
    qr_code_data: 'COL26-REG:COL26-SPT-001004|EVT:evt_spt_g_14|NAME:Ananya Deshmukh|COLLEGE:IIT Madras',
    created_at: '2026-10-04T09:45:00Z'
  },
  {
    id: 'reg_05',
    registration_id: 'COL26-CUL-001005',
    event_id: 'evt_cul_10',
    user_id: 'usr_part_05',
    participant_name: 'Rohan Sengupta',
    participant_email: 'rohan.sen@jadavpur.edu',
    participant_phone: '+91 98302 55667',
    participant_college: 'Jadavpur University, Kolkata',
    participation_type: 'individual',
    team_size: 1,
    emergency_contact_name: 'Tapan Sengupta',
    emergency_contact_phone: '+91 98302 44332',
    status: 'confirmed',
    qr_code_data: 'COL26-REG:COL26-CUL-001005|EVT:evt_cul_10|NAME:Rohan Sengupta|COLLEGE:Jadavpur',
    created_at: '2026-10-05T16:20:00Z'
  },
  {
    id: 'reg_06',
    registration_id: 'COL26-CUL-001006',
    event_id: 'evt_cul_04',
    user_id: 'usr_part_06',
    participant_name: 'Sneha Ramamurthy',
    participant_email: 'sneha.r@mcc.edu',
    participant_phone: '+91 98409 66778',
    participant_college: 'Madras Christian College, Chennai',
    participation_type: 'individual',
    team_size: 1,
    emergency_contact_name: 'G. Ramamurthy',
    emergency_contact_phone: '+91 98409 33221',
    status: 'checked_in',
    qr_code_data: 'COL26-REG:COL26-CUL-001006|EVT:evt_cul_04|NAME:Sneha Ramamurthy|COLLEGE:MCC',
    created_at: '2026-10-05T17:00:00Z'
  },
  {
    id: 'reg_07',
    registration_id: 'COL26-SPT-001007',
    event_id: 'evt_spt_b_13',
    user_id: 'usr_part_07',
    participant_name: 'Siddharth Kaushik',
    participant_email: 'sid.kaushik@psgtech.edu',
    participant_phone: '+91 97890 77889',
    participant_college: 'PSG College of Technology, Coimbatore',
    participation_type: 'individual',
    team_size: 1,
    emergency_contact_name: 'M. Kaushik',
    emergency_contact_phone: '+91 97890 11223',
    status: 'checked_in',
    qr_code_data: 'COL26-REG:COL26-SPT-001007|EVT:evt_spt_b_13|NAME:Siddharth Kaushik|COLLEGE:PSG Tech',
    created_at: '2026-10-06T10:10:00Z'
  },
  {
    id: 'reg_08',
    registration_id: 'COL26-CUL-001008',
    event_id: 'evt_cul_01',
    user_id: 'usr_part_08',
    participant_name: 'Priyanka Sen',
    participant_email: 'priyanka.sen@bengaluruarts.edu',
    participant_phone: '+91 99001 88990',
    participant_college: 'College of Fine Arts, Bengaluru',
    participation_type: 'individual',
    team_size: 1,
    emergency_contact_name: 'B. Sen',
    emergency_contact_phone: '+91 99001 22334',
    status: 'checked_in',
    qr_code_data: 'COL26-REG:COL26-CUL-001008|EVT:evt_cul_01|NAME:Priyanka Sen|COLLEGE:CFA Bengaluru',
    created_at: '2026-10-06T11:45:00Z'
  },
  {
    id: 'reg_09',
    registration_id: 'COL26-CUL-001009',
    event_id: 'evt_cul_02',
    user_id: 'usr_part_09',
    participant_name: 'Dhruv Ratnam',
    participant_email: 'dhruv.r@nid.ac.in',
    participant_phone: '+91 98791 99001',
    participant_college: 'National Institute of Design, Ahmedabad',
    participation_type: 'individual',
    team_size: 1,
    emergency_contact_name: 'S. Ratnam',
    emergency_contact_phone: '+91 98791 33445',
    status: 'checked_in',
    qr_code_data: 'COL26-REG:COL26-CUL-001009|EVT:evt_cul_02|NAME:Dhruv Ratnam|COLLEGE:NID',
    created_at: '2026-10-06T12:00:00Z'
  },
  {
    id: 'reg_10',
    registration_id: 'COL26-CUL-001010',
    event_id: 'evt_cul_02',
    user_id: 'usr_part_10',
    participant_name: 'Samyuktha Iyer',
    participant_email: 'samyuktha.i@stellamaris.edu',
    participant_phone: '+91 98412 11224',
    participant_college: 'Stella Maris College, Chennai',
    participation_type: 'individual',
    team_size: 1,
    emergency_contact_name: 'N. Iyer',
    emergency_contact_phone: '+91 98412 88776',
    status: 'checked_in',
    qr_code_data: 'COL26-REG:COL26-CUL-001010|EVT:evt_cul_02|NAME:Samyuktha Iyer|COLLEGE:Stella Maris',
    created_at: '2026-10-06T13:30:00Z'
  },
  {
    id: 'reg_11',
    registration_id: 'COL26-CUL-001011',
    event_id: 'evt_cul_03',
    user_id: 'usr_part_01',
    participant_name: 'Aarav Sharma',
    participant_email: 'aarav.sharma@xavier.edu',
    participant_phone: '+91 98210 11223',
    participant_college: "St. Xavier's College, Mumbai",
    participation_type: 'team',
    team_name: 'Electric Mirage',
    team_size: 5,
    emergency_contact_name: 'Sunil Sharma',
    emergency_contact_phone: '+91 98210 99887',
    status: 'confirmed',
    qr_code_data: 'COL26-REG:COL26-CUL-001011|EVT:evt_cul_03|NAME:Aarav Sharma|COLLEGE:St. Xavier',
    created_at: '2026-10-06T14:10:00Z'
  },
  {
    id: 'reg_12',
    registration_id: 'COL26-CUL-001012',
    event_id: 'evt_cul_05',
    user_id: 'usr_part_02',
    participant_name: 'Diya Krishnan',
    participant_email: 'diya.krishnan@loyola.edu',
    participant_phone: '+91 98401 22334',
    participant_college: 'Loyola College, Chennai',
    participation_type: 'team',
    team_name: 'Loyola Dynamic Crew',
    team_size: 12,
    emergency_contact_name: 'P. Krishnan',
    emergency_contact_phone: '+91 98401 88776',
    status: 'confirmed',
    qr_code_data: 'COL26-REG:COL26-CUL-001012|EVT:evt_cul_05|NAME:Diya Krishnan|COLLEGE:Loyola',
    created_at: '2026-10-07T09:15:00Z'
  },
  {
    id: 'reg_13',
    registration_id: 'COL26-CUL-001013',
    event_id: 'evt_cul_06',
    user_id: 'usr_part_06',
    participant_name: 'Sneha Ramamurthy',
    participant_email: 'sneha.r@mcc.edu',
    participant_phone: '+91 98409 66778',
    participant_college: 'Madras Christian College, Chennai',
    participation_type: 'team',
    team_name: 'MCC Theatrical Vanguard',
    team_size: 18,
    emergency_contact_name: 'G. Ramamurthy',
    emergency_contact_phone: '+91 98409 33221',
    status: 'confirmed',
    qr_code_data: 'COL26-REG:COL26-CUL-001013|EVT:evt_cul_06|NAME:Sneha Ramamurthy|COLLEGE:MCC',
    created_at: '2026-10-07T10:30:00Z'
  },
  {
    id: 'reg_14',
    registration_id: 'COL26-CUL-001014',
    event_id: 'evt_cul_07',
    user_id: 'usr_part_05',
    participant_name: 'Rohan Sengupta',
    participant_email: 'rohan.sen@jadavpur.edu',
    participant_phone: '+91 98302 55667',
    participant_college: 'Jadavpur University, Kolkata',
    participation_type: 'team',
    team_name: 'Kolkata Street Players',
    team_size: 10,
    emergency_contact_name: 'Tapan Sengupta',
    emergency_contact_phone: '+91 98302 44332',
    status: 'confirmed',
    qr_code_data: 'COL26-REG:COL26-CUL-001014|EVT:evt_cul_07|NAME:Rohan Sengupta|COLLEGE:Jadavpur',
    created_at: '2026-10-07T11:45:00Z'
  },
  {
    id: 'reg_15',
    registration_id: 'COL26-CUL-001015',
    event_id: 'evt_cul_08',
    user_id: 'usr_part_09',
    participant_name: 'Dhruv Ratnam',
    participant_email: 'dhruv.r@nid.ac.in',
    participant_phone: '+91 98791 99001',
    participant_college: 'National Institute of Design, Ahmedabad',
    participation_type: 'team',
    team_name: 'Avant-Garde Studio',
    team_size: 14,
    emergency_contact_name: 'S. Ratnam',
    emergency_contact_phone: '+91 98791 33445',
    status: 'confirmed',
    qr_code_data: 'COL26-REG:COL26-CUL-001015|EVT:evt_cul_08|NAME:Dhruv Ratnam|COLLEGE:NID',
    created_at: '2026-10-07T13:20:00Z'
  },
  {
    id: 'reg_16',
    registration_id: 'COL26-CUL-001016',
    event_id: 'evt_cul_09',
    user_id: 'usr_part_04',
    participant_name: 'Ananya Deshmukh',
    participant_email: 'ananya.d@iitm.ac.in',
    participant_phone: '+91 94451 44556',
    participant_college: 'IIT Madras',
    participation_type: 'individual',
    team_size: 1,
    emergency_contact_name: 'V. Deshmukh',
    emergency_contact_phone: '+91 94451 66554',
    status: 'confirmed',
    qr_code_data: 'COL26-REG:COL26-CUL-001016|EVT:evt_cul_09|NAME:Ananya Deshmukh|COLLEGE:IIT Madras',
    created_at: '2026-10-08T09:00:00Z'
  },
  {
    id: 'reg_17',
    registration_id: 'COL26-SPT-001017',
    event_id: 'evt_spt_b_12',
    user_id: 'usr_part_03',
    participant_name: 'Kabir Mehta',
    participant_email: 'kabir.mehta@bits.edu',
    participant_phone: '+91 97112 33445',
    participant_college: 'BITS Pilani',
    participation_type: 'team',
    team_name: 'BITS Spikers',
    team_size: 8,
    emergency_contact_name: 'Rajiv Mehta',
    emergency_contact_phone: '+91 97112 77665',
    status: 'confirmed',
    qr_code_data: 'COL26-REG:COL26-SPT-001017|EVT:evt_spt_b_12|NAME:Kabir Mehta|COLLEGE:BITS Pilani',
    created_at: '2026-10-08T10:15:00Z'
  },
  {
    id: 'reg_18',
    registration_id: 'COL26-SPT-001018',
    event_id: 'evt_spt_g_15',
    user_id: 'usr_part_10',
    participant_name: 'Samyuktha Iyer',
    participant_email: 'samyuktha.i@stellamaris.edu',
    participant_phone: '+91 98412 11224',
    participant_college: 'Stella Maris College, Chennai',
    participation_type: 'individual',
    team_size: 1,
    emergency_contact_name: 'N. Iyer',
    emergency_contact_phone: '+91 98412 88776',
    status: 'confirmed',
    qr_code_data: 'COL26-REG:COL26-SPT-001018|EVT:evt_spt_g_15|NAME:Samyuktha Iyer|COLLEGE:Stella Maris',
    created_at: '2026-10-08T11:30:00Z'
  },
  {
    id: 'reg_19',
    registration_id: 'COL26-SPT-001019',
    event_id: 'evt_spt_g_16',
    user_id: 'usr_part_02',
    participant_name: 'Diya Krishnan',
    participant_email: 'diya.krishnan@loyola.edu',
    participant_phone: '+91 98401 22334',
    participant_college: 'Loyola College, Chennai',
    participation_type: 'individual',
    team_size: 1,
    emergency_contact_name: 'P. Krishnan',
    emergency_contact_phone: '+91 98401 88776',
    status: 'confirmed',
    qr_code_data: 'COL26-REG:COL26-SPT-001019|EVT:evt_spt_g_16|NAME:Diya Krishnan|COLLEGE:Loyola',
    created_at: '2026-10-08T14:45:00Z'
  },
  {
    id: 'reg_20',
    registration_id: 'COL26-CUL-001020',
    event_id: 'evt_cul_10',
    user_id: 'usr_part_01',
    participant_name: 'Aarav Sharma',
    participant_email: 'aarav.sharma@xavier.edu',
    participant_phone: '+91 98210 11223',
    participant_college: "St. Xavier's College, Mumbai",
    participation_type: 'individual',
    team_size: 1,
    emergency_contact_name: 'Sunil Sharma',
    emergency_contact_phone: '+91 98210 99887',
    status: 'confirmed',
    qr_code_data: 'COL26-REG:COL26-CUL-001020|EVT:evt_cul_10|NAME:Aarav Sharma|COLLEGE:St. Xavier',
    created_at: '2026-10-08T16:00:00Z'
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_01',
    user_id: 'usr_part_01',
    title: 'Registration Confirmed: Basketball Boys',
    message: 'Your registration COL26-SPT-001001 has been confirmed. View your Digital QR Pass on My Dashboard.',
    category: 'checkin',
    priority: 'important',
    is_read: false,
    action_url: '/dashboard',
    created_at: '2026-10-14T08:00:00Z'
  },
  {
    id: 'notif_02',
    title: 'Venue Notice: Dr. APJ Abdul Kalam Auditorium',
    message: 'Soundcheck for Solo Music and Band begins at 13:00 hrs sharp. Please report backstage.',
    category: 'reminder',
    priority: 'urgent',
    is_read: false,
    action_url: '/schedule',
    created_at: '2026-10-14T09:15:00Z'
  },
  {
    id: 'notif_03',
    title: 'Results Published: Boys Table Tennis',
    message: 'Results for Boys Singles have been declared. Gold medal awarded to PSG Tech.',
    category: 'result',
    priority: 'normal',
    is_read: false,
    action_url: '/results',
    created_at: '2026-10-15T17:05:00Z'
  },
  {
    id: 'notif_04',
    title: 'Welcome to COLORIDO 2K26!',
    message: 'Explore all 16 cultural and sports disciplines and build your personal festival itinerary.',
    category: 'system',
    priority: 'normal',
    is_read: true,
    action_url: '/events',
    created_at: '2026-10-10T10:00:00Z'
  }
];

export const INITIAL_CERTIFICATES: CertificateItem[] = [
  {
    id: 'cert_01',
    certificate_id: 'CERT-COL26-W001',
    registration_id: 'COL26-SPT-001001',
    event_id: 'evt_spt_b_11',
    event_name: 'Basketball Championship — Boys',
    participant_name: 'Aryan Nair & St. Xavier Ballers',
    college: "St. Xavier's College, Mumbai",
    certificate_type: 'Winner Certificate',
    achievement: 'Winner — 1st Place (Gold Medal)',
    issue_date: '2026-10-16',
    authorized_signatory_1: 'Dr. Arvind Sharma (Festival Convener)',
    authorized_signatory_2: 'Prof. Sunita Rao (Dean Student Affairs)',
    verification_hash: 'SHA256-COL26-BASKETBALL-XAVIER-GOLD-8472'
  },
  {
    id: 'cert_02',
    certificate_id: 'CERT-COL26-W002',
    registration_id: 'COL26-CUL-001009',
    event_id: 'evt_cul_02',
    event_name: 'Music & Band — Solo (Vocal / Instrumental)',
    participant_name: 'Dhruv Ratnam',
    college: 'National Institute of Design, Ahmedabad',
    certificate_type: 'Winner Certificate',
    achievement: 'Winner — 1st Place (Gold Trophy)',
    issue_date: '2026-10-16',
    authorized_signatory_1: 'Dr. Arvind Sharma (Festival Convener)',
    authorized_signatory_2: 'Prof. Sunita Rao (Dean Student Affairs)',
    verification_hash: 'SHA256-COL26-MUSIC-NID-GOLD-9921'
  },
  {
    id: 'cert_03',
    certificate_id: 'CERT-COL26-P003',
    registration_id: 'COL26-CUL-001002',
    event_id: 'evt_cul_01',
    event_name: 'Fine Arts Exhibition & Live Canvas',
    participant_name: 'Diya Krishnan',
    college: 'Loyola College, Chennai',
    certificate_type: 'Participation Certificate',
    achievement: 'Official Participant & Exhibitor',
    issue_date: '2026-10-16',
    authorized_signatory_1: 'Dr. Arvind Sharma (Festival Convener)',
    authorized_signatory_2: 'Prof. Sunita Rao (Dean Student Affairs)',
    verification_hash: 'SHA256-COL26-FINEARTS-LOYOLA-PART-1123'
  }
];

export const DEMO_USERS: UserProfile[] = [
  {
    id: 'usr_part_01',
    email: 'student@colorido2k26.edu',
    full_name: 'Aarav Sharma',
    phone: '+91 98210 11223',
    college: "St. Xavier's College, Mumbai",
    department: 'Computer Science',
    year: '3rd Year',
    role: 'participant',
    avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80'
  },
  {
    id: 'usr_coord_01',
    email: 'coordinator@colorido2k26.edu',
    full_name: 'Ananya Deshmukh',
    phone: '+91 98451 22341',
    college: 'Host University Event Secretariat',
    department: 'Fine Arts & Stage Operations',
    year: 'Faculty Coordinator',
    role: 'coordinator',
    coordinator_status: 'approved',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80'
  },
  {
    id: 'usr_admin_01',
    email: 'admin@colorido2k26.edu',
    full_name: 'Festival Secretariat Admin',
    phone: '+91 98860 00001',
    college: 'COLORIDO 2K26 Central Executive Committee',
    department: 'Central Administration',
    year: 'Director General',
    role: 'admin',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80'
  }
];
